from django.contrib import admin
from django.urls import path
from flower_shop_app import views
urlpatterns = [
    path('',views.firstpage),
    path('homepage',views.homepage),
    path('adminlogin',views.adminlogin),
    path('adminpage',views.adminpage),
    path('checklog',views.checklog),
    path('adminlogout',views.adminlogout),
    path('addflower1',views.addflower1),
    path('adminstore',views.adminstore),
    path('adminhome',views.adminhome),
    path('adminrecord/<int:id>',views.adminrecord),
    path('adminupdata/<int:id>',views.adminupdata),
    path('goback',views.goback),
    path('deleterecord/<int:id>',views.deleterecord),
    path('adminvieworder',views.adminvieworder),
    path('customerlogin',views.customerlogin),
    path('customerhomepage',views.customerhomepage),
    path('customerchecklog',views.customerchecklog),
    path('customersignup',views.customersignup),
    path('new_login_reaister',views.new_login_reaister),
    path('customerstore',views.customerstore),
    path('customerlogout',views.customerlogout),
    path('customertable',views.customertable),
    path('hometable',views.hometable),
    path('cartstore/<int:id>',views.cartstore),
    path('cartpage',views.cartpage),
    # path('adddetails',views.adddetails),
    path('cartorder',views.cartorder),
    path('buypage/<int:id>',views.buypage),
    path('orderstore/<int:id>',views.orderstore),
    path('yourorder',views.yourorder),
    path('review/<int:id>',views.review),
    path('statusupdate/<int:id>',views.statusupdate),
    path('orderstatusupdate/<int:id>',views.orderstatusupdate),
    path('reviewstore/<int:id>',views.reviewstore),
    path('adminrevieworder',views.adminrevieworder),
    path('yourfeedback/<int:id>',views.yourfeedback),
    path('customerfeedback/<int:id>',views.customerfeedback),
    path('adminfeedbackview',views.adminfeedbackview),
    
       
]