# Generated by Django 4.1.5 on 2023-03-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flower_id', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=10)),
                ('flower_name', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('flower_image', models.FileField(blank=True, max_length=500, null=True, upload_to='')),
                ('order_quantity', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=10)),
                ('total_price', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'Add_cart',
            },
        ),
        migrations.CreateModel(
            name='flower_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flower_id', models.CharField(max_length=10)),
                ('flower_name', models.CharField(max_length=25)),
                ('flower_category', models.CharField(max_length=25)),
                ('flower_price', models.CharField(max_length=100)),
                ('flower_image', models.FileField(blank=True, null=True, upload_to='')),
            ],
            options={
                'db_table': 'flower_details',
            },
        ),
        migrations.CreateModel(
            name='new_login_reaister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=10)),
                ('user_phone_no', models.CharField(max_length=10)),
                ('user_email', models.CharField(max_length=50)),
                ('user_password', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'new_login_reaister',
            },
        ),
        migrations.CreateModel(
            name='order_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flower_id', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=15)),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('name', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('phone_no', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=500)),
                ('username', models.CharField(max_length=25)),
                ('order_quantity', models.CharField(max_length=20)),
                ('amount', models.CharField(max_length=20)),
                ('total_amount', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('review', models.CharField(max_length=30)),
                ('feedback', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'order_details',
            },
        ),
    ]
